from abc import ABC, abstractmethod
from typing import Any, Dict

class IntegrationAdapter(ABC):
    @abstractmethod
    def validate_config(self) -> None: ...
    @abstractmethod
    def health(self) -> Dict[str, Any]: ...
    @abstractmethod
    def capabilities(self) -> Dict[str, Any]: ...
    @abstractmethod
    def execute(self, operation: str, payload: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    def audit_metadata(self) -> Dict[str, Any]: ...
